### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by AganRun** [pawlaczyk/sarenka#27]
How can I start this project, can you give me a document or a brief description

**Comment by pawlaczyk** [comment]
Hi,
Please check README.md  in  branch https://github.com/pawlaczyk/sarenka/tree/**building-app**
**sarenka.py** script is crucial it creates all database (863 sqlite3 files)

It's Django on backend + React on frontend, and instead of creating many database on backend everything is standard and communication is via Django Rest Framework (on <server_adress>:8000 there is a swagger and all endpoints description).

**Comment by pawlaczyk** [comment]
Hi, Please check branch master. 
In next 72h we should test manually everything, so bear in mind it might not be stable yet.
