### ISSUE TITLE
Please!!!

### ISSUE THREAD

**Issue by lyxwz** [pawlaczyk/sarenka#28]
Hello, my teacher let me reactor your sarenka subject. and i download the github‘s code and open it with the pycharm, but i don't know how to run it . Can you update the description of installing it, Please~~

**Comment by pawlaczyk** [comment]
Hi, I just installed and tested app on Windows (on Linux should works also)
Please check README.md and sarenka.py branch https://github.com/pawlaczyk/sarenka/tree/**building-app** I added raw instruction for you. 
**sarenka.py** script is crucial it creates all database (863 sqlite3 files)

I will reply to you later, because in Poland is 5:42AM.

**Comment by pawlaczyk** [comment]
Hi, Please check branch master. 
In next 72h we should test manually everything, so bear in mind it might not be stable yet.
